### ISSUE TITLE
Leng Becomes Unresponsive

### ISSUE THREAD

**Issue by seang96** [Cottand/leng#55]
I am experiencing a new issue on v1.5.1 where leng stops responding to DNS requests. The service tends to barely use any CPU, but when an iPhone (IP is 172.16.16.159) suddenly sends a bunch of DNS requests, usage spikes up by 4-10 times normal usage and at this point, DNS requests will fail for 5-10 minutes. My current workaround is to kill the service if it fails to perform lookups (livenessProbe) and restart itself; since I am running it in a cluster, there are 2 other replicas that cover for it while it restarts. In the last 27 hours, it has failed 80 times.

[Here is a gist containing my config and logs](https://gist.github.com/seang96/b1c6d3cf993f8d231197b4d9fadf1443)

I ran Pihole previously with the same blocked sources, so I am thinking its likely some issue with leng or some weird iOS update since I only started noticing this about a week ago.

Thanks!

**Comment by Cottand** [comment]
hi! thanks for the report and for including logs and config. Do you hav more concrete steps to reproduce this so that I can debug on my end on a test? How many requests/s do you consider 'a bunch'?

**Comment by seang96** [comment]
Thanks for the response.

It's the last bit of the log that it occurs starting with

21:12:37.063 INFO handler.go:125 ▶ 306c[0m 172.16.16.159 lookup　gateway.fe2.apple-dns.net IN A

557 requests within 29 seconds.

**Comment by Cottand** [comment]
- whitelisting regex: no, I am afraid whitelisting is an exact match only. Adding regex would be possible, but I imagine it would slow things down a bit, because it's the hot path and would require iterating through the entire whitelist. Please make a new issue if this is something you would like!
- reproducing: alright thanks! I will try to spam leng with a bunch of requests over the weekend and see if I can reproduce and fix this. 600 requests over 30s is definitely something leng should be able to handle.

**Comment by seang96** [comment]
My current theory is the iPhone freaks out from one of these not being accessible, but I don't think I saw any item being blocked in the logs either, so the regex whitelist is probably not necessary.

I also wanted to note I think it can handle the amount of requests too and even reports it with Prometheus metrics, though it stops responding to DNS requests even inside the container itself.

**Comment by Cottand** [comment]
@seang96 I could not reproduce this, even for a larger amount of requests than what you described. I did about 5k requests over a few seconds.

I mixed custom and normal records and used a dumb small script like:
```bash
bash -c 'set -eux
    for i in $(seq 1 1000);
    do
      dig @10.10.4.1 google.com &
      dig @10.10.4.1 grafana.traefik &
      dig @10.10.4.1 nico.dcotta.eu &
      dig @10.10.4.1 example.com &
      dig @10.10.4.1 apple.com &
      echo  "done $i"
    done'
```
This was in my leng deployment (see [permalink](https://github.com/Cottand/selfhosted/blob/05f3eab00ed5505e2c8f79a8a2af274d46096780/jobs/dns.hcl)) but targeting a single host, 10.10.4.1, so there should not have been any load balancing. I ran the script from the same host leng was running on.

Console output did not seem to indicate leng was unresponsive"
```
; <<>> DiG 9.18.21 <<>> @10.10.4.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25831
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		83	IN	A	216.58.212.174

;; Query time: 0 msec
;; SERVER: 10.10.4.1#53(10.10.4.1) (UDP)
;; WHEN: Sat Feb 24 19:31:44 GMT 2024
;; MSG SIZE  rcvd: 65
```

See the following grafana panels:
<img width="747" alt="image" src="https://github.com/Cottand/leng/assets/45274424/597fe2e8-4507-4487-84b4-7857dfa2ae20">
(there is some delay in reporting the metrics on leng's side, but that is not something I believe to be related)


Maybe you could point to some specific problematic records so that I could `dig` the same ones as your phone?

**Comment by Cottand** [comment]
If you can compile a list of domains to test, I could test them against my leng installation yes 👍  . 

You may find it useful to [enable high cardinality metrics](https://cottand.github.io/leng/Prometheus-Metrics.html#high-cardinality-metrics) which will make leng also include the domains in the `request_total` metric.

**Comment by seang96** [comment]
@Cottand I figured grimd might be good to test and since running it, grimd has not stopped responding to DNS requests, so it looks like grimd either had the issue prior to forking and fixed it or the bug was introduced after forking it.

I haven't had the time to test leng further, but I figured this would be useful info.

Thanks!

**Comment by Cottand** [comment]
@seang96 thank you! that is useful. I checked and grimd has not received any updates (at all) since I forked it.

I will try to browse through the diff to try and guess what might have broken it for you, but even if I do find something, it will be impossible for me to test whether that was it on my end. If you could come up with some testing script (like [here](https://github.com/Cottand/leng/issues/55#issuecomment-1962661909)) that would be a big help!

**Comment by seang96** [comment]
Sounds good. I still plan on doing the script though I ran into hardware failure so my cluster is a little full with only 2 nodes while the other is being shipped for repairs. It will probably be a couple weeks before I get it back so I can actually test it on my environment.

Thanks for the continued support!

**Comment by seang96** [comment]
I have been testing leng on my network again for 2 weeks without this issue occurring now. I assume the dependency updates helped or maybe the iPhone getting updates resolved this.

Thanks for the support on this and sorry for the delay in trying to reproduce it.
