### ISSUE TITLE
Adding mutiple dns over https and dot. 

### ISSUE THREAD

**Issue by t-e-s-tweb** [Cottand/leng#69]
Hello, as mentioned in another issue from somebody else, would it be possible to add dot for upstream and also multiple doh for upstream so it uses random server from the list or used two servers picked randomly or a single random server for each query. that would improve the privacy and also if some server isn't available even then the queries would work. This is how its implemented in blocky. Leng is the best in memory usage and everything else only issue is that it uses a single upstream.

**Comment by cottand** [comment]
Hey, thanks for your feedback. You mention several features, so not sure which of these you are looking for. Are you looking for something like [blocky's `upstreams.strategy`](https://0xerr0r.github.io/blocky/latest/configuration/#upstream-strategy)?

I will work to better document this, but currently leng will use upstreams on the same protocol (DoT, TCP, or UDP) as the query it got. But if you have set the DoH upstream, then it tries that one first in order to preserve privacy.

For example, if have in your config:
```toml
[Upstream]
    DoH = "https://cloudflare-dns.com/dns-query"
    nameservers = ["1.1.1.1:53", "1.0.0.1:53"]
```
...and you query `example.com` on DoT, then leng will 
- try DoH via `cloudflare-dns.com/dns-query` first
- if that fails, then it will try _both_ 1.1.1.1 and 1.0.0.1 via DoT
- then reply with whichever comes back first.

If what you are worried about is not that DoH provider will discover all your queries, defaulting to DoH should be pretty privacy preserving as everything is encrypted by default. Using several DoH for reliability is also usually not necessary because HTTP itself is load-balanced and a lookup of the DoH upstream host itself returns several IPs.


If you are worried about your provider (in this example, cloudflare) discovering your queries, my very opinionated response is that randomly selecting an upstream **is not a good way to do this**. Your upstreams will still see 50-25% of your queries depending on how many of them you have. Once your caching expires, they will see _a different 50-25%_. After some period of time, they will have probably seen all of your queries. The authoritative servers will still see your queries for their domains, [but that is inevitable with DNS](https://www.reddit.com/r/selfhosted/comments/a3jxpm/comment/eb6vmey/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

If you are worried about preserving your privacy with your upstream, I strongly suggest you use something like [unbound](https://github.com/NLnetLabs/unbound) which is fully recursive (unlike leng, blocky, or CoreDNS), and will forward queries to the right authoritative DNS chain.

If you like using blocky or leng, then I suggest you use them and set unbound as your upstream.

**Comment by cottand** [comment]
hey @t-e-s-tweb does this answer your question? If so, are you happy to close the issue?
